import type { PlayerRecord } from './types'

export function buildPlayerRecord(overrides: Partial<PlayerRecord> = {}): PlayerRecord {
  return {
    id: 1,
    slug: 'sample-player',
    displayName: 'Sample Player',
    firstName: 'Sample',
    lastName: 'Player',
    isCurrentPlayer: true,
    isDefunctFranchise: false,
    teamId: 1610612752,
    teamAbbreviation: 'NYK',
    teamName: 'New York Knicks',
    conference: 'East',
    division: 'Atlantic',
    position: 'G',
    positionTokens: ['G'],
    heightInInches: 78,
    heightCm: 198,
    currentAge: 26,
    birthDate: null,
    jerseyNumber: 4,
    headshotUrl: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1.png',
    country: 'USA',
    college: 'Duke',
    draft: {
      year: 2020,
      round: 1,
      pick: 8,
      teamId: 1610612752,
      teamAbbreviation: 'NYK',
      teamName: 'New York Knicks',
      isUndrafted: false,
    },
    entryDraftYear: 2020,
    entryDraftYearSource: 'draft',
    career: {
      debutYear: 2020,
      finalSeasonYear: 2025,
      seasonsPlayed: 6,
      preNbaPath: 'Duke',
      careerTeamIds: [1610612752],
      careerTeamAbbreviations: ['NYK'],
      careerTeamNames: ['New York Knicks'],
      previousTeamIds: [],
      previousTeamAbbreviations: [],
      previousTeamNames: [],
      allStarAppearances: 0,
      allNbaSelections: 0,
      allDefensiveSelections: 0,
      championships: 0,
      finalsMvpAwards: 0,
      mvpAwards: 0,
      rookieOfTheYearAwards: 0,
      defensivePlayerOfTheYearAwards: 0,
      scoringTitles: 0,
      reboundTitles: 0,
      assistTitles: 0,
      isHallOfFame: false,
      isGreatest75: false,
      accolades: [],
      primaryAccolade: null,
      hasRichMetadata: true,
    },
    snapshot: {
      pointsPerGame: 14.4,
      reboundsPerGame: 4.2,
      assistsPerGame: 5.1,
      minutesPerGame: 24.6,
      playoffPicture: true,
      playoffRank: 4,
      careerAccoladeLabel: null,
    },
    flags: {
      isRookie: false,
      isInternational: false,
      isAllStar: false,
      isUnder25: false,
    },
    searchText: 'sample player nyk',
    ...overrides,
  }
}
